# Generated by Django 3.0.8 on 2020-07-17 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='acta',
            name='año',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2099)]),
        ),
        migrations.AddField(
            model_name='acta',
            name='número',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
