# Generated by Django 3.0.8 on 2020-07-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo',
            field=models.CharField(choices=[('pre', 'Pregrado'), ('pos', 'Posgrado')], default='pre', max_length=3),
        ),
    ]
