# Generated by Django 3.1.7 on 2021-03-20 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uapapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapapp.dependencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
