# Generated by Django 3.0.8 on 2020-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo',
            field=models.CharField(choices=[('Pre', 'Pregrado'), ('Pos', 'Posgrado')], default='PRE', max_length=3),
        ),
    ]
