# Generated by Django 3.1.7 on 2021-03-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp', '0002_usuariodependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
