# Generated by Django 3.1.7 on 2021-03-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp', '0003_programa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
